{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Server`s status' %}{% endblock %}

{% set active_menu = 'serverstatus' %}

{% block content %}

<div class="widget first">
    <div class="head">
        <h5>{% trans 'Server`s status' %}</h5>
    </div>

    <div class="help">
        <h3>{% trans 'Moduł Statystyk Serwerów' %}</h3>
    </div>

     <table class="tableStatic wide">
        
        <thead>
                    <tr>
                        <td width="3%">&nbsp;</td>
                        <td width="20%">Host</td>
                        <td>WWW</td>
                        <td>MAIL</td>
                        <td>FTP</td>
                        <td style="width: 21%;">Akcje</td>
                    </tr>
                </thead>
                
        <tbody>
   {% for stat in host %}
   
   		<tr>
                <td>{{stat['name']}}</td>
   						<td width="20%">{{stat['host']}}</td>
                        <td>WWW</td>
                        <td>MAIL</td>
                        <td>FTP</td>
                        <td style="width: 21%;">Akcje</td>
   {% endfor %}

        </tbody>
    </table>
    
</div>

{% endblock %}